### ISSUE TITLE
Problem using a 3x3 matrix

### ISSUE THREAD

**Issue by jaumesastretomas** [maclandrol/FisherExact#5]
Hi, I am using the following matrix:
# 3 3
159     4       80
3       25      0
30      0       108

And I obtained the pvalue=0

Why is that?

Is not possible to use mxm matrices?

Thanks.

**Comment by maclandrol** [comment]
It should definitively work. I got :

Pvalue : 1.50266533e-47

I assume you are using the binary. There was a bug in the pvalue printing that was fixed in commit cdf4684c5 some while ago. If you install using the github repository, then there shouldn't be any problem. However I forgot to update the pypi version so the bug was still there (binary only). I fixed it. 

Thanks.

**Comment by jaumesastretomas** [comment]
Ok now it worked!

I re-installed the binary.

thanks.

Jaume

2018-02-22 7:27 GMT+01:00 Emmanuel Noutahi <notifications@github.com>:
